# Generated by Django 5.2.6 on 2025-09-22 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_jobcategory_jobtag_companyprofile_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='company',
        ),
        migrations.RemoveField(
            model_name='job',
            name='category',
        ),
        migrations.RemoveField(
            model_name='job',
            name='tags',
        ),
        migrations.DeleteModel(
            name='CompanyProfile',
        ),
        migrations.DeleteModel(
            name='JobCategory',
        ),
        migrations.DeleteModel(
            name='Job',
        ),
        migrations.DeleteModel(
            name='JobTag',
        ),
    ]
