# Generated by Django 5.2.6 on 2025-09-27 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_job_company_remove_job_category_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='emailotp',
            constraint=models.UniqueConstraint(fields=('user', 'purpose', 'code'), name='unique_user_purpose_code'),
        ),
    ]
