# Minimal Render service template (example). Configure via Render dashboard for actual deployment.
services:
  - type: web
    name: nexus-backend
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: backend.production_settings
      - key: SECRET_KEY
        generateValue: true
      - key: DJANGO_ALLOWED_HOSTS
        value: "nexus-backend.onrender.com"
      - key: DATABASE_URL
        fromDatabase:
          name: nexus-db
          property: connectionString
      - key: EMAIL_BACKEND
        value: django.core.mail.backends.console.EmailBackend

databases:
  - name: nexus-db
    databaseName: nexus
    user: nexus
    plan: free
